### ISSUE TITLE
Talk about early versions

### ISSUE THREAD

**Issue by pmiossec** [pmiossec/vscode-gitextensions#1]
@erikleo I have released a new version containing the commands in the status bar.

You could have a try...

**Comment by erikleo** [comment]
@pmiossec .. Installed and works great!  Thanks so much for the work on this.  I think it is great productivity increase.

Only thing I could think of adding would be a setting to choose which buttons you want to show on the bottom.  (I only need the browse one).

Are you planing on releasing through vs code extensions search?  Once it is finalized i show to people on team who I think will also be interested.

one other thing the link on in the readme.md to release section seems to be broken.

**Comment by pmiossec** [comment]
>Only thing I could think of adding would be a setting to choose which buttons you want to show on the bottom. (I only need the browse one).

Planned ;-)

>Are you planing on releasing through vs code extensions search? Once it is finalized i show to people on team who I think will also be interested.

Also planned ;-)

>one other thing the link on in the readme.md to release section seems to be broken.

Thanks. I put a (bad) relative link and forgot to test it.

**Comment by erikleo** [comment]
sounds great.  2 More ideas I have for the future are: 

1) Put an indication on the "Gitextensions browse" icon button if there are pending commits (similar to the built in git in vs code)

2) figure out if a gitextions with the current repo is already open, and if this is the case,  just bring the window to the front instead of opening a new instance of Git extensions.  I have already seen that if multiple are open you can not do commits.

**Comment by pmiossec** [comment]
> Put an indication on the "Gitextensions browse" icon button if there are pending commits (similar to the built in git in vs code)

Not sure if it's a good idea... 2 possibilities:

* the git support is enabled, so the information is already displayed in the status bar
* the git support is disabled, so I have to retrieve the information myself and that's the begining of a huge work to reimplement the git support in the extension (that I don't have the time and wish to do!)


>figure out if a gitextions with the current repo is already open, and if this is the case, just bring the window to the front instead of opening a new instance of Git extensions.

That's not possible at the moment with GitExtensions. That require a lot of changes in it that I don't want to do (no time for it)

>I have already seen that if multiple are open you can not do commits.

Never seens a problem like that. Perhaps you should reproduce it and create an issue.

**Comment by pmiossec** [comment]
Extensions published on the marketplace with the settings to hide the icons

**Comment by erikleo** [comment]
Install from marketplace is working for me, but I don't see how to change setting to hide icons.  Is it under "Manage Extension" or do i need to add json to the main settings?

**Comment by pmiossec** [comment]
No, go to "User settings" (use the command palette, or "File > preferences > settings" or "Gear" icon > "Settings) and search for "GitExtensions". 

You should find 2 settings that you could easily modify (there is an edit icon appearing in the gutter when you over them)

**Comment by erikleo** [comment]
got it.  Works great

**Comment by pmiossec** [comment]
I think I can close this issue...
