### ISSUE TITLE
Add commands to the Explorer context menu

### ISSUE THREAD

**Issue by RandScullard** [pmiossec/vscode-gitextensions#2]
It would be great if you could add these three commands to the Explorer context menu (package.json: contributes.menus explorer/context):

- GitExtensions: See in Diff Tool
- GitExtensions: See File History
- GitExtensions: Reset changes

Then it would work just like the GitExtensions add-in for Visual Studio! (Since I have to jump back and forth between VSCode and VS2015, the more I can make them work the same, the less my head hurts.)

**Comment by pmiossec** [comment]
good idea.
Thanks also for the tip.
I have already made something but that need some polishing....

>GitExtensions: Reset changes

Do you really mean "reset" which is a global command that reset all the changes of all the files. It seems not good for me to add it to the explorer contextual menu for a file.

I think we should prefer "revert file" instead...that works on one file.

**Comment by RandScullard** [comment]
Whoops! Yes, I meant revert that one file. Thanks for catching that!

**Comment by pmiossec** [comment]
Done (in v0.4).

Could you tell me if "GitExtensions: See in Diff Tool" is working for you. 
It don't for me. But it seems more a problem with GitExtensions config....

Feel free to close the issue if all works for you.

**Comment by RandScullard** [comment]
It works great! Thanks for getting that done so quickly.
